# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHistoriaUsuario3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_historiaUsuario3(self):
    self.driver.get("https://pascualbravo.ingejei.com/shop/")
    self.driver.set_window_size(697, 703)
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-product:nth-child(2) .attachment-woocommerce_thumbnail").click()
    self.driver.find_element(By.NAME, "add-to-cart").click()
    self.driver.find_element(By.LINK_TEXT, "Ver carrito").click()
    self.driver.find_element(By.CSS_SELECTOR, ".wc-block-cart-item__remove-link").click()
    self.driver.close()
  
