# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHistoriaUsuario5():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_historiaUsuario5(self):
    self.driver.get("https://pascualbravo.ingejei.com/wp-login.php?action=lostpassword")
    self.driver.set_window_size(697, 703)
    self.driver.find_element(By.ID, "user_login").click()
    self.driver.find_element(By.ID, "user_login").send_keys("kvalencia373@gmail.com")
    self.driver.find_element(By.ID, "wp-submit").click()
    self.driver.close()
  
